version: '3.8'

services:
  backend: # Backend servisimizin adı
    build: ./backend # Backend klasöründeki Dockerfile'ı kullan
    container_name: blogadd-backend
    ports:
      - "5000:5000" # Host makinedeki 5000 portunu konteynerdeki 5000 portuna yönlendir
    environment:
      # Ortam değişkenlerini burada tanımlayın. MONGO_URI, 'db' servisine işaret ediyor.
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://db:27017/blogapp # Önemli: Docker Compose ağı içinde 'db' adı geçerli olacak
      JWT_SECRET: cok-gizli-anahtar
      SESSION_SECRET: baska-bir-cok-gizli-anahtar
    depends_on:
      - db # Backend servisi, db servisi başlamadan başlamaz (sıralama garantisi verir)
    volumes:
      - ./backend:/app # Geliştirme sırasında kod değişikliklerinin yansıması için
      - /app/node_modules # node_modules klasörünü host'a bağlamayarak bağımlılık sorunlarını önler

  db: # MongoDB servisimizin adı
    image: mongo:latest
    container_name: blogadd-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Verilerin kalıcı olması için bir volume bağla
    environment:
      TZ: Europe/Berlin

volumes:
  mongo_data: # MongoDB verileri için kalıcı bir volume tanımla