version: '3.8'

services:
  backend: # Backend servisimizin adı
    build: ./backend
    container_name: blogadd-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://db:27017/blogapp
      - JWT_SECRET=cok-gizli-anahtar
      - SESSION_SECRET=baska-bir-cok-gizli-anahtar
    depends_on:
      - db
    volumes: # <-- BURAYI GÜNCELLEYİN
      - ./backend:/app # Geliştirme sırasında kod değişikliklerinin yansıması için
      - ./uploads:/app/uploads # <-- YENİ EKLENEN SATIR: Host'taki uploads klasörünü container'daki /app/uploads'a eşle
      - /app/node_modules # node_modules klasörünü host'a bağlamayarak bağımlılık sorunlarını önler

  db: # MongoDB servisimizin adı
    image: mongo:latest
    container_name: blogadd-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Verilerin kalıcı olması için bir volume bağla
    environment:
      TZ: Europe/Berlin

volumes:
  mongo_data: # MongoDB verileri için kalıcı bir volume tanımla