###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "test@example.com",
    "password": "password123"
}


###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "tester",
    "email": "tester@example.com",
    "password": "testpassword"
}


###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password123"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "tester@example.com",
    "password": "testpassword"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NzNmMzlmMDk0MzM3NDg3Y2U5ZGE5MyIsImlhdCI6MTc1MjUwOTQzNiwiZXhwIjoxNzUyNTEzMDM2fQ.OsuveP2At-hQXn5CbMMbo4ln6CYUby8rs92gvuWv8N4

{
    "title": "İlk Blog Yazım2",
    "content": "Bu benim Docker ve Node.js ile oluşturduğum ilk harika blog yazım!"
}

###
GET http://localhost:5000/api/posts


###
PUT http://localhost:5000/api/posts/68752c915df1baf5fb1423e8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NzNmMzlmMDk0MzM3NDg3Y2U5ZGE5MyIsImlhdCI6MTc1MjUwOTQzNiwiZXhwIjoxNzUyNTEzMDM2fQ.OsuveP2At-hQXn5CbMMbo4ln6CYUby8rs92gvuWv8N4

{
    "title": "Güncellenmiş İlk Blog Yazım (Yeni Başlık)",
    "content": "Bu yazı şimdi güncellendi ve hala çok güzel! Docker ile çalışmak harika."
}

###
DELETE http://localhost:5000/api/posts/68752c915df1baf5fb1423e8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NzNmMzlmMDk0MzM3NDg3Y2U5ZGE5MyIsImlhdCI6MTc1MjUwOTQzNiwiZXhwIjoxNzUyNTEzMDM2fQ.OsuveP2At-hQXn5CbMMbo4ln6CYUby8rs92gvuWv8N4